# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bb91146fb5c5c673092b1437cb679a311cc053cead31e8e3d6a56169c5e66bbf5a9e51f3da659cd74cd0a5d2d2795883327f2ef3f4e81b14aa124f4dfa643ca

test:
  secret_key_base: 34cd005a614f83fbbfa801a67500f9506150e233de23181449e99ea403c1bdc5346c990169bd23bc149b80c3fc80960b3696ba6eea8182c95f075404bef5e2b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
